+#toc: @tocrow |number - III| |title - The Stranger| tocrow@
+#bibliography: @arendt: ! Hannah Arendt, The Human Condition, 1958, Chicago !

#chapter_three
@chapter |number - III| |title - The Stranger|
The hatch opens anyway. A stranger hauls themselves up, soaked through.
chapter@
chapter_three#
